export const colors = {
  textGreen: "text-[#fff]",
  textBrown: "text-[#fff]",
  textYellow: "text-[#fff]",
  textRed: "text-[#fff]",
  textBlue: "text-[#fff]",
  textBlue2: "text-[#fff]",
  textPurple: "text-[#fff]",
  textOrange: "text-[#fff]",
  bgGreen: "bg-[#4caf50]",
  bgBrown: "bg-[#795548]",
  bgYellow: "bg-[#ff9800]",
  bgRed: "bg-[#f44336]",
  bgBlue: "bg-[#2196f3]",
  bgBlue2: "bg-[#009688]",
  bgPurple: "bg-[#673ab7]",
  bgOrange: "bg-[#ff7800]",
};

// export const colors = {
//   textGreen: "text-[#4caf50]",
//   textBrown: "text-[#795548]",
//   textYellow: "text-[#ff9800]",
//   textRed: "text-[#f44336]",
//   textBlue: "text-[#2196f3]",
//   textBlue2: "text-[#009688]",
//   textPurple: "text-[#673ab7]",
//   textOrange: "text-[#ff7800]",
//   bgGreen: "bg-[#e6ffed]",
//   bgBrown: "bg-[#efebe9]",
//   bgYellow: "bg-[#ffecb3]",
//   bgRed: "bg-[#ffdddd]",
//   bgBlue: "bg-[#c6dbff]",
//   bgBlue2: "bg-[#93e2da]",
//   bgPurple: "bg-[#e7d0ff]",
//   bgOrange: "bg-[#ffcda1]",
// };
